# Generated by Django 4.1.5 on 2023-01-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COEMaster',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('CoeDivision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecurrenceMaster',
            fields=[
                ('Rid', models.IntegerField(primary_key=True, serialize=False)),
                ('AssignedDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Repeatition', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('Role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Rname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('Uid', models.IntegerField(primary_key=True, serialize=False)),
                ('Uname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('TId', models.IntegerField(primary_key=True, serialize=False)),
                ('Tname', models.CharField(max_length=50)),
                ('TDescription', models.TextField(max_length=500)),
                ('Category', models.CharField(max_length=15)),
                ('Tpriority', models.CharField(max_length=10)),
                ('status', models.CharField(default='Unassigned', max_length=10)),
                ('Attachment', models.FileField(max_length=254, upload_to=None)),
                ('CID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.coemaster')),
                ('Rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.recurrencemaster')),
                ('Role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.rolemaster')),
                ('UID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='MailMaster',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('CID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.coemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('Mail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('FromEmail', models.EmailField(max_length=200)),
                ('Subject', models.CharField(max_length=255)),
                ('MailBody', models.TextField(max_length=500)),
                ('ToEmail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.mailmaster')),
            ],
        ),
    ]
