# Generated by Django 4.1.5 on 2023-01-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmaster',
            name='CID',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.DeleteModel(
            name='MailMaster',
        ),
    ]
