# Generated by Django 4.1.5 on 2023-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0002_remove_mailmaster_cid_delete_mail_delete_mailmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='Utype',
            field=models.CharField(default='User', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='isactive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
