# Generated by Django 4.1.5 on 2023-02-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0003_usermaster_utype_usermaster_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='CID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CFO.coemaster'),
        ),
        migrations.AlterField(
            model_name='coemaster',
            name='CID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recurrencemaster',
            name='Rid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='Role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='TId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='Uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='isactive',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
