# Generated by Django 4.1.5 on 2023-02-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0004_usermaster_cid_alter_coemaster_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='CID',
            field=models.IntegerField(null=True),
        ),
    ]
