# Generated by Django 4.1.5 on 2023-02-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0005_alter_usermaster_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='CID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Rid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Role_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='UID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='CID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
