# Generated by Django 4.1.5 on 2023-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0006_alter_taskmaster_cid_alter_taskmaster_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencemaster',
            name='Rname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
