# Generated by Django 4.1.5 on 2023-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0007_recurrencemaster_rname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='isactive',
            field=models.CharField(default='Inactive', max_length=255, null=True),
        ),
    ]
