# Generated by Django 4.1.5 on 2023-02-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0008_alter_usermaster_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmaster',
            name='Rid',
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='Rname',
            field=models.ManyToManyField(to='CFO.recurrencemaster'),
        ),
    ]
