# Generated by Django 4.1.5 on 2023-02-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0009_remove_taskmaster_rid_taskmaster_rname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmaster',
            name='Rname',
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='Rname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
